### ISSUE TITLE
Suggestion: Write Log to File by Default

### ISSUE THREAD

**Issue by MidnightOnMars** [eduadiez/DAppNodePackage-prysm-validator#2]
It appears logs are written to stdout, but for a testnet it might make sense to preserve logs by default.

My validator was slashed and ejected while running uninterrupted and I wasn't able to provide the team with the log file for analysis.

**Comment by eduadiez** [comment]
You are totally right!

In theory, from http://my.dappnode/#/packages/prysm-validator.public.dappnode.eth/logs you can download all the logs of the package by clicking on `Download all`, but I've found an issue related to that: https://github.com/dappnode/DNP_DAPPMANAGER/issues/302, I hope we can fix it soon.

In any case, I added a couple of parameters to the package:
* `--log-file=/var/log/validator.log`
So now you can always download the validator logs from its [file-manager](http://my.dappnode/#/packages/prysm-validator.public.dappnode.eth/file-manager)

* `--verbosity=${VERBOSITY}`
This allows you to choose the log level for the validator (info by default)

* `EXTRA_OPTS`
In this configuration parameter you can add other options to the validator on the [configure](http://my.dappnode/?#/packages/prysm-validator.public.dappnode.eth/config) view

I just published version 0.1.4 with these improvements in addition to updating both, the beacon-chain package and the validator, to the latest version: `HEAD-e3c3de`

**Comment by MidnightOnMars** [comment]
Thanks for the quick update - just updated to the newest DAppNode package and started with a fresh validator!
